[build]
  base = "PolylineWebFactory"
  command = "npm ci && npm run build"
  publish = "dist/Polyline-Development/browser"  # <-- respeta el casing que pida el plugin
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
