[build]
  command = "cd PolylineWebFactory && npm ci && npm run build"
  publish = "PolylineWebFactory/dist/polyline-development/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
