[build]
  command = "npm ci && npm run build"
  publish = "dist/Polyline-Development/browser"
  functions = "netlify/functions"

# (Opcional) si el plugin te molesta con el publish, elimínalo en la UI de Netlify
# o quítalo de netlify.toml si lo tuvieras aquí.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
